# Generated by Django 6.0.7 on 2026-07-30 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='What the project does')),
                ('priority_area', models.CharField(choices=[('Arts', 'Arts'), ('Community Development', 'Community Development'), ('Culture', 'Culture'), ('Downtown Development', 'Downtown Development'), ('Economic Development', 'Economic Development'), ('Education', 'Education'), ('Food Access', 'Food Access'), ('Health', 'Health'), ('Housing', 'Housing'), ('Human Services', 'Human Services'), ('Literacy', 'Literacy'), ('Public Safety', 'Public Safety'), ('Recreation', 'Recreation'), ('Workforce Development', 'Workforce Development'), ('Youth Development', 'Youth Development')], max_length=64)),
                ('ntee_code', models.CharField(blank=True, max_length=32)),
                ('location_city', models.CharField(max_length=120)),
                ('location_state', models.CharField(max_length=2)),
                ('org_type', models.CharField(choices=[('501c3', '501(c)(3)'), ('government', 'Government'), ('school', 'School'), ('other', 'Other')], max_length=32)),
                ('budget_requested', models.DecimalField(decimal_places=2, max_digits=14)),
                ('eligibility_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'grant_project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funder_name', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('grants_gov', 'Grants.gov'), ('usaspending', 'USASpending'), ('propublica', 'ProPublica')], max_length=32)),
                ('score', models.FloatField()),
                ('reasoning', models.TextField()),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='projects.project')),
            ],
            options={
                'verbose_name': 'Match result',
                'verbose_name_plural': 'Match results',
                'db_table': 'grant_match_result',
                'ordering': ['-created_at'],
            },
        ),
    ]
