# Generated by Django 6.0.7 on 2026-07-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='budget_requested',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, help_text='What the work does'),
        ),
        migrations.AddField(
            model_name='profile',
            name='eligibility_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='location_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='ntee_code',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='org_type',
            field=models.CharField(blank=True, choices=[('501c3', '501(c)(3)'), ('government', 'Government'), ('school', 'School'), ('other', 'Other')], max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='priority_area',
            field=models.CharField(blank=True, choices=[('Arts', 'Arts'), ('Community Development', 'Community Development'), ('Culture', 'Culture'), ('Downtown Development', 'Downtown Development'), ('Economic Development', 'Economic Development'), ('Education', 'Education'), ('Food Access', 'Food Access'), ('Health', 'Health'), ('Housing', 'Housing'), ('Human Services', 'Human Services'), ('Literacy', 'Literacy'), ('Public Safety', 'Public Safety'), ('Recreation', 'Recreation'), ('Workforce Development', 'Workforce Development'), ('Youth Development', 'Youth Development')], max_length=64),
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text='What you seek funding for', max_length=255),
        ),
    ]
