# Generated by Django 6.0.7 on 2026-07-31 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_budget_requested_profile_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('grants_gov', 'Grants.gov'), ('usaspending', 'USASpending')], max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('deadline', models.CharField(blank=True, max_length=64)),
                ('url', models.CharField(blank=True, max_length=1000)),
                ('opp_status', models.CharField(blank=True, max_length=120)),
                ('number', models.CharField(blank=True, max_length=120)),
                ('amount', models.CharField(blank=True, max_length=64)),
                ('score', models.FloatField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_grants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved grant',
                'verbose_name_plural': 'Saved grants',
                'db_table': 'grant_saved',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'external_id'), name='uniq_user_source_external_grant')],
            },
        ),
    ]
