# Generated by Django 6.0.7 on 2026-07-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_savedgrant'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgrant',
            name='agency_address',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='savedgrant',
            name='agency_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='savedgrant',
            name='top_agency',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
