# Generated by Django 6.0.7 on 2026-08-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_starterprompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedgrant',
            name='category',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
