# Generated by Django 6.0.7 on 2026-08-10 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_savedgrant_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weekly_digest_enabled',
            field=models.BooleanField(default=True, help_text='Send this user the Monday grant digest email.'),
        ),
        migrations.CreateModel(
            name='WeeklyDigestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=16)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('match_count', models.PositiveIntegerField(default=0)),
                ('webhook_status', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_digests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Weekly digest log',
                'verbose_name_plural': 'Weekly digest logs',
                'db_table': 'grant_weekly_digest_log',
                'ordering': ['-week_start', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'week_start'), name='uniq_user_week_digest')],
            },
        ),
    ]
