# Generated by Django 6.0.7 on 2026-09-10 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_weekly_digest_enabled_weeklydigestlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=32)),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('verdict', models.CharField(choices=[('good_match', 'Eligible / good match'), ('not_eligible', 'Not eligible'), ('irrelevant', 'Irrelevant')], max_length=32)),
                ('note', models.TextField(blank=True, help_text='Optional why-not from the user')),
                ('title', models.CharField(blank=True, max_length=500)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('pop_state', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grant feedback',
                'verbose_name_plural': 'Grant feedback',
                'db_table': 'grant_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'verdict'], name='idx_feedback_user_verdict')],
                'constraints': [models.UniqueConstraint(fields=('user', 'source', 'external_id'), name='uniq_user_source_external_feedback')],
            },
        ),
    ]
