# Generated by Django 6.0.7 on 2026-09-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_grantfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentInstructionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('feedback_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('skipped', 'Skipped')], max_length=16)),
                ('method', models.CharField(blank=True, choices=[('ai', 'AI summary of reasons'), ('summary', 'Pattern summary (AI unavailable)')], max_length=16)),
                ('guidance', models.TextField(blank=True, help_text="Rules appended to the agent instructions, one '- ' bullet per line.")),
                ('detail', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent instruction update',
                'verbose_name_plural': 'Agent instruction updates',
                'db_table': 'grant_agent_instruction_update',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='grantfeedback',
            name='note',
            field=models.TextField(blank=True, help_text='The reason the user gave for this verdict'),
        ),
    ]
