# Generated by Django 6.0.7 on 2026-09-14 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_agentinstructionupdate_alter_grantfeedback_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentinstructionupdate',
            name='conflict_feedback_ids',
            field=models.JSONField(blank=True, default=list, help_text="Feedback rows whose reasons caused this run's changes."),
        ),
        migrations.AlterField(
            model_name='agentinstructionupdate',
            name='guidance',
            field=models.TextField(blank=True, help_text="What this run changed, one '- ' line per change."),
        ),
        migrations.AlterField(
            model_name='agentinstructionupdate',
            name='method',
            field=models.CharField(blank=True, choices=[('ai', 'AI'), ('summary', 'Pattern summary (older runs)')], max_length=16),
        ),
        migrations.CreateModel(
            name='AgentSystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('content', models.TextField(help_text='The full system prompt, in Markdown.')),
                ('source', models.CharField(choices=[('file', 'Imported from grant_agent_instructions.md'), ('weekly', 'Weekly feedback patch'), ('manual', 'Edited in admin')], default='manual', max_length=16)),
                ('change_summary', models.TextField(blank=True, help_text='What changed from the version it is based on.')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('based_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.agentsystemprompt')),
            ],
            options={
                'verbose_name': 'Agent system prompt',
                'verbose_name_plural': 'Agent system prompts',
                'db_table': 'grant_agent_system_prompt',
                'ordering': ['-version'],
            },
        ),
        migrations.AddField(
            model_name='agentinstructionupdate',
            name='prompt',
            field=models.ForeignKey(blank=True, help_text='The prompt version this run created.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updates', to='accounts.agentsystemprompt'),
        ),
        migrations.AddConstraint(
            model_name='agentsystemprompt',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_agent_system_prompt'),
        ),
    ]
