# Generated by Django 6.0.7 on 2026-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_seed_agent_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgrant',
            name='source',
            field=models.CharField(choices=[('grants_gov', 'Grants.gov'), ('usaspending', 'USASpending'), ('granted_ai', 'GrantedAI'), ('simpler_grants', 'Simpler.Grants.gov')], max_length=32),
        ),
    ]
