# Generated by Django 6.0.7 on 2026-09-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_savedgrant_simpler_grants_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedgrant',
            name='source',
            field=models.CharField(choices=[('grants_gov', 'Grants.gov'), ('usaspending', 'USASpending'), ('granted_ai', 'GrantedAI'), ('simpler_grants', 'Simpler.Grants.gov'), ('opengrants', 'OpenGrants')], max_length=32),
        ),
    ]
