# Generated by Django 6.0.7 on 2026-09-29 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_savedgrant_opengrants_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFoundation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=9)),
                ('name', models.CharField(max_length=255)),
                ('priority_area', models.CharField(blank=True, max_length=64)),
                ('score', models.FloatField(blank=True, null=True)),
                ('top_categories', models.JSONField(blank=True, default=list)),
                ('grants_in_category', models.IntegerField(default=0)),
                ('amount_in_category', models.FloatField(default=0)),
                ('typical_grant', models.FloatField(default=0)),
                ('michigan_grants_pct', models.FloatField(default=0)),
                ('accepts_requests', models.BooleanField(null=True)),
                ('contact', models.JSONField(blank=True, null=True)),
                ('example_grants', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_foundations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved foundation',
                'verbose_name_plural': 'Saved foundations',
                'db_table': 'grant_saved_foundation',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'ein'), name='uniq_user_saved_foundation')],
            },
        ),
    ]
