# Generated by Django 6.0.7 on 2026-09-29 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_savedfoundation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title_locked',
            field=models.BooleanField(default=False),
        ),
    ]
