# Generated by Django 6.0.7 on 2026-09-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_conversation_title_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfoundation',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='savedgrant',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
