# Generated by Django 6.0.7 on 2026-09-28 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sub_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('ntee_code', models.CharField(blank=True, max_length=10)),
                ('subsection_code', models.IntegerField(blank=True, null=True)),
                ('raw_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FunderContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('accepts_unsolicited', models.BooleanField(null=True)),
                ('notes', models.TextField(blank=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funders.funder')),
            ],
        ),
        migrations.CreateModel(
            name='PastGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=255)),
                ('recipient_city', models.CharField(blank=True, max_length=100)),
                ('recipient_state', models.CharField(blank=True, max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, null=True)),
                ('purpose', models.TextField(blank=True)),
                ('tax_year', models.IntegerField(null=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funders.funder')),
            ],
        ),
    ]
