# Generated by Django 6.0.7 on 2026-09-28 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_id', models.CharField(max_length=50, unique=True)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('tax_period', models.CharField(blank=True, max_length=10)),
                ('batch_id', models.CharField(blank=True, max_length=50)),
                ('processed', models.BooleanField(default=False)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funders.funder')),
            ],
        ),
    ]
