# Generated by Django 6.0.7 on 2026-09-28 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0002_filing'),
    ]

    operations = [
        migrations.AddField(
            model_name='filing',
            name='grant_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='filing',
            name='only_preselected',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='fundercontact',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='funders.filing'),
        ),
        migrations.AddField(
            model_name='pastgrant',
            name='filing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grants', to='funders.filing'),
        ),
    ]
