# Generated by Django 6.0.7 on 2026-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0003_filing_grant_count_filing_only_preselected_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrantClassificationCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('recipient_norm', models.CharField(max_length=255)),
                ('purpose_norm', models.TextField(blank=True)),
                ('label', models.CharField(max_length=50)),
                ('model_used', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='pastgrant',
            name='classified_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='pastgrant',
            name='priority_area',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
