# Generated by Django 6.0.7 on 2026-09-29 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funders', '0004_grantclassificationcache_pastgrant_classified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_breakdown', models.JSONField(default=dict)),
                ('top_categories', models.JSONField(default=list)),
                ('total_grants', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('avg_grant_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('michigan_grants_count', models.IntegerField(default=0)),
                ('michigan_grants_pct', models.FloatField(default=0)),
                ('years_with_data', models.JSONField(default=list)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('funder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='funders.funder')),
            ],
        ),
    ]
