-- ============================================================================
--  Chat starter prompts (predefined cards) — customizable text + queries
--  Table: grant_starter_prompt   (Postgres / Supabase)
--
--  These rows drive the four cards on the empty-chat screen
--  ("Find grants", "Update my project", "View saved", "Ask anything").
--  Edit title/description to change what is shown; edit `query` to change what
--  gets passed to the grant matcher (with the saved profile) for SEARCH cards.
--
--  If the table is empty, the app falls back to the built-in defaults, so the
--  chat never breaks.
-- ============================================================================

-- --------------------------------------------------------------------------
-- 1) Create the table.
--
--    PREFERRED: instead of running this DDL by hand, just run the Django
--    migration, which creates the table AND records it:
--        python manage.py migrate accounts
--
--    Only run the CREATE TABLE below if you are provisioning purely by SQL.
--    If you do, tell Django the migration is already applied so it won't try
--    to create the table again:
--        python manage.py migrate accounts 0006_starterprompt --fake
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS grant_starter_prompt (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key         VARCHAR(64)  NOT NULL UNIQUE,
    title       VARCHAR(120) NOT NULL,
    description VARCHAR(200) NOT NULL DEFAULT '',
    action      VARCHAR(32)  NOT NULL DEFAULT 'search',   -- search | update_project | link | focus_input
    query       VARCHAR(500) NOT NULL DEFAULT '',         -- SEARCH cards: text passed to the matcher
    href        VARCHAR(300) NOT NULL DEFAULT '',          -- LINK cards: URL to open
    position    INTEGER      NOT NULL DEFAULT 0 CHECK (position >= 0),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

-- --------------------------------------------------------------------------
-- 2) Seed the four default cards (idempotent — safe to re-run).
--    ON CONFLICT (key) keeps existing rows if you already customized them.
-- --------------------------------------------------------------------------
INSERT INTO grant_starter_prompt
    (key,            title,               description,                 action,           query,          href,                position, is_active, created_at, updated_at)
VALUES
    ('find_grants',    'Find grants',       'Search by focus & location', 'search',         'find grants',  '',                  0, TRUE, now(), now()),
    ('update_project', 'Update my project', 'Refresh intake details',     'update_project', '',             '',                  1, TRUE, now(), now()),
    ('view_saved',     'View saved',        'Open grants you saved',      'link',           '',             '/accounts/saved/',  2, TRUE, now(), now()),
    ('ask_anything',   'Ask anything',      'Type a question below',      'focus_input',    '',             '',                  3, TRUE, now(), now())
ON CONFLICT (key) DO NOTHING;

-- ============================================================================
--  HOW TO CUSTOMIZE (examples) — edit the shown text and/or the passed query.
-- ============================================================================

-- Change the label + subtitle of the first card:
-- UPDATE grant_starter_prompt
--    SET title = 'Find funding', description = 'Best matches for your project', updated_at = now()
--  WHERE key = 'find_grants';

-- Change the query a SEARCH card passes to the model (with the saved profile).
-- e.g. make it always search California education grants:
-- UPDATE grant_starter_prompt
--    SET query = 'find education grants in California', updated_at = now()
--  WHERE key = 'find_grants';

-- Add a brand-new SEARCH card:
-- INSERT INTO grant_starter_prompt (key, title, description, action, query, position)
-- VALUES ('housing_ca', 'Housing in CA', 'Affordable housing funding', 'search',
--         'find housing grants in California', 4);

-- Hide a card without deleting it:
-- UPDATE grant_starter_prompt SET is_active = FALSE, updated_at = now() WHERE key = 'view_saved';

-- Reorder cards (lower position shows first):
-- UPDATE grant_starter_prompt SET position = 0, updated_at = now() WHERE key = 'update_project';
